FROM ubuntu:18.04
MAINTAINER Zac Scott <zac@zacscott.net>
CMD apt update
CMD apt install python3.6 rsync
CMD curl -sL https://deb.nodesource.com/setup_8.x | bash -
CMD apt update
CMD apt install npm
CMD pip3 install ansible
